### ISSUE TITLE
I cannot open a note in a new window

### ISSUE THREAD

**Issue by Kenljs** [ras0q/obsidian-graph-banner#26]
When I try to open a note in a new window (not a new tab) the local graph view takes over the whole note. This occurs with whatever note I open in a new window.

**Comment by ras0q** [comment]
@Kenljs Does this bug also occur in v1.0.3?
Would you attach a screenshot or video if reproduced?

**Comment by Kenljs** [comment]
Hello! I did update and this is the result.



Before the update, when I opened a new note it took over the whole note. Now the note is blank.

additionally, in my other notes that are tabs (not a new window) the graph is not displaying for the current note, but for a different note that is no longer even open.

![image](https://github.com/ras0q/obsidian-graph-banner/assets/97832807/c11334fd-05d0-44d8-b088-53eacb09d540)

**Comment by Kenljs** [comment]
It happens when I try to open up a note in a new window.

Here is the debug info, if that helps.
Also, it does not happen in sandbox mode. Hmm. I'm not sure what other plugin would be messing with this.

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: Windows 11 Home 10.0.22631
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: light
	Community theme: Minimal v7.5.4
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 70
	Plugins enabled: 37
		1: Better Command Palette v0.17.1
		2: Chronology v1.1.11
		3: Excalidraw v2.2.6
		4: Imgur v2.5.2
		5: Linter v1.24.0
		6: Minimal Theme Settings v8.0.2
		7: Note Toolbar v1.7.28
		8: Copy document as HTML v0.7.0
		9: Folder Note v0.7.3
		10: Footnote Shortcut v0.1.3
		11: Hotkeys++ v0.2.7
		12: Note Refactor v1.8.2
		13: Pandoc Plugin v0.4.1
		14: Quick Switcher++ v4.2.2
		15: Readwise Official v2.0.1
		16: Slash Commander v0.2.16
		17: Smarter Markdown Hotkeys v1.16.4
		18: Tag Wrangler v0.6.1
		19: Style Settings v1.0.8
		20: Templater v2.3.3
		21: ToggleList v1.2.6
		22: Underline v1.3.0
		23: Waypoint v2.1.0
		24: Whisper v1.5.5
		25: Commander v0.5.1
		26: Task Progress Bar v2.0.0
		27: Plugin Update Tracker v1.5.2
		28: Mousewheel Image zoom v1.0.22
		29: Alias Management v0.0.1
		30: Emoji Toolbar v0.4.1
		31: Awesome Flashcard v0.1.2
		32: Local Backup v0.1.7
		33: Copy Block Link v1.0.4
		34: Dictionary v2.22.0
		35: Dangerzone Writing v0.0.11
		36: Paste image rename v1.6.1
		37: Graph Banner v1.0.3

**Comment by Kenljs** [comment]
Another hint at the solution.
* **When I go into appearance settings and turn off "minimal theme" then graph banner works.**

**Comment by ras0q** [comment]
@Kenljs In v1.3.2, I changed the way to open the graph. Could you check to see if the issue has been fixed?

**Comment by Kenljs** [comment]
Now it is a different issue. When I open a new window I can see the note (which is different than before) but I can no longer see the nodes on the graph.


![image](https://github.com/user-attachments/assets/a2b0503e-fb02-4018-9227-48f18d3b336a)

**Comment by ras0q** [comment]
@Kenljs 
Umm... Has it been fixed by trying to restart the application, reinstall the plugin, etc.?
 The process has been changed considerably and may conflict with the behavior of previous versions.

**Comment by Kenljs** [comment]
I restarted obsidian after uninstalling and then reinstalling the plugin. Still to no avail. 🤔

**Comment by Kenljs** [comment]
I really have no idea what I'm doing, so forgive me if I'm not giving you relevant information. After looking for errors in the dev tools this is what I found.

When I open a new tab with the graph that doesn't show right, and then I press open dev tools, there are no errors.


But if I go back to my home tab, and then I open dev tools there are errors. Here is a screenshot of what I see as the errors. I don't know if they're related.


![image](https://github.com/user-attachments/assets/50d329bc-e93f-4056-8cf1-5b3c7b885c06)

I tried to copy/paste the error below

```
<html>
<body>
<!--StartFragment--><div tabindex="-1" class="console-group console-group-messages" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; color: rgb(31, 31, 31); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div tabindex="-1" class="console-message-wrapper console-error-level console-selected" jslog="Item; context: console-message; track: click, keydown: ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Enter|Space|Home|End" role="log" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: #a00; --console-color-green: #0a0; --console-color-yellow: #a50; --console-color-blue: #00a; --console-color-magenta: #a0a; --console-color-cyan: #0aa; --console-color-gray: #aaa; --console-color-darkgray: #555; --console-color-lightred: #f55; --console-color-lightgreen: #5f5; --console-color-lightyellow: #ff5; --console-color-lightblue: #55f; --console-color-ightmagenta: #f5f; --console-color-lightcyan: #5ff; --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error);"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="pixi.min.js:1017 Uncaught TypeError: Cannot read properties of null (reading 'render')
    at zn.render (pixi.min.js:1017:36362)
    at renderCallback (app.js:1:2097399) Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" role="link" tabindex="-1" title="app://obsidian.md/lib/pixi.min.js:1017" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">pixi.min.js:1017</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of null (reading 'render')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at zn.render (<button class="devtools-link text-button link-style" role="link" tabindex="-1" title="app://obsidian.md/lib/pixi.min.js:1017:36362" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">pixi.min.js:1017:36362</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at renderCallback (<button class="devtools-link text-button link-style" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:2097399" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; word-break: break-all;">app.js:1:2097399</button>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 474.222px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | render | @ | pixi.min.js:1017
-- | -- | -- | --
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1
  | requestAnimationFrame (async) |   |  
  | e.queueRender | @ | app.js:1
  | renderCallback | @ | app.js:1

</span></div></div></div></div></div></div></div><br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by ras0q** [comment]
The situation wa reproruced! I'll look into it further.

https://github.com/user-attachments/assets/50cc728c-919c-4049-9ff5-009aa90a498f

**Comment by ras0q** [comment]
As a work-around at this time, opening a new window from the menu seems to display the graph 🤔 


https://github.com/user-attachments/assets/c4719366-1528-4510-aa71-de71f632b163

**Comment by Kenljs** [comment]
Great! So glad you could reproduce it. 

That is good to know about the workaround. So funny that opening it from that menu Wouldn't cause the issue.

Thank you for your work on this graph! I know its all volunteer work. This plugin was a great idea!
